version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.20.0
    - 4.21.0
  - dependency-name: typescript
    versions:
    - 4.2.4
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.16
    - 13.1.1
    - 13.1.2
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.2
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.6
  - dependency-name: "@types/node"
    versions:
    - 14.14.37
